# Generated by Django 6.0.7 on 2026-07-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['business_name'], 'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Temporarily open or close your restaurant.'),
        ),
    ]
