# Generated by Django 6.0.7 on 2026-07-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='menu_cart_user_id_ba9ab7_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='menu_cart_session_80a7da_idx',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
