# Generated by Django 6.0.7 on 2026-07-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='choose a category', max_length=120, unique=True),
        ),
    ]
