# Generated by Django 6.0.7 on 2026-07-30 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_category_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('protein', models.FloatField(default=0.0)),
                ('carbs', models.FloatField(default=0.0)),
                ('fats', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_selectable_items', models.PositiveIntegerField(default=1)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Ingredient Categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='mood_icons/')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_customizable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CustomBowl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customizations', to='menu.menuitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_bowls', to=settings.AUTH_USER_MODEL)),
                ('selected_ingredients', models.ManyToManyField(related_name='custom_bowls_selected', to='menu.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='base_ingredients',
            field=models.ManyToManyField(blank=True, related_name='menu_items_original', to='menu.ingredient'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menu.ingredientcategory'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='moods',
            field=models.ManyToManyField(blank=True, related_name='menu_items_original', to='menu.mood'),
        ),
    ]
