# Generated by Django 6.0.7 on 2026-07-30 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_ingredient_ingredientcategory_mood_and_more'),
        ('vendors', '0002_alter_vendor_options_alter_vendor_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombowl',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_bowls', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='ingredientcategory',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_categories', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='mood',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moods', to='vendors.vendor'),
        ),
    ]
