# Generated by Django 6.0.7 on 2026-07-29 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_orders', models.BooleanField(default=True)),
                ('notify_status', models.BooleanField(default=True)),
                ('notify_reviews', models.BooleanField(default=True)),
                ('notify_push', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=False)),
                ('notify_marketing', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
